name: flutter_open_weather
description: A new Flutter project by open weather.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  http: ^0.13.5
  intl: ^0.18.0
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/cloud.png
    - images/wind.png
    - images/humidity.png
